# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod tidy

# https://goreleaser.com/customization/builds/
builds:
  - main: ./cmd/namigo
    id: namigo
    binary: namigo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath

# https://goreleaser.com/customization/changelog/
changelog:
  sort: asc
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - "^(Refactor|Update|Rename)" # common chore
      - "^(Migrate|Normalize|Reformat|Remove|Shorten)" # uncommon chore
      - comment
      - test
      - unused

# https://goreleaser.com/customization/release/
release:
  github:
    owner: huangsam
    name: namigo
  name_template: "v{{ .Version }}"
